### ISSUE TITLE
Trying to build "master" branch on ubuntu 12.04

### ISSUE THREAD

**Issue by fabiencastan** [mikrosimage/duke#4]
Hi,

I don't achieved to build duke "master" branch on my ubuntu 12.04.

Build errors:
http://pastebin.com/rVuwas3u

My user-config.jam:
http://pastebin.com/cYLbT8mx

Fabien

**Comment by gchatelet** [comment]
This comes from the SFML's version. You have to stick to the one in the [documentation](https://github.com/mikrosimage/duke/blob/master/INSTALL.md).
