### ISSUE TITLE
Compilation with libAV need cmake variables ?

### ISSUE THREAD

**Issue by stephane-lb** [mikrosimage/duke#52]
Hi all,

I tried to compile Duke (branch develop) on Centos 6, and some problems appear with libAV.

``` bash
[ 93%] Building CXX object src/duke/CMakeFiles/duke.dir/imageio_plugins/libav/LibAv.cpp.o
/tmp/duke/src/duke/imageio_plugins/libav/LibAv.cpp:19:30: fatal error: libavutil/avutil.h: No such file or directory
 #include <libavutil/avutil.h>
                              ^
compilation terminated.
make[2]: *** [src/duke/CMakeFiles/duke.dir/imageio_plugins/libav/LibAv.cpp.o] Error 1
make[1]: *** [src/duke/CMakeFiles/duke.dir/all] Error 2
make: *** [all] Error 2
```

Do you think it will be a good idea to have libAv in the dependencies ? Or at least have the ability to not using it ? 

Regards,
Stephan

**Comment by gchatelet** [comment]
Hi Stephan,

Sorry for the late reply, I was out of the country/without internet connection for the past 10 days.
You're absolutely right LibAv should be optional/configurable this is planned but not done yet. I'll report here when it's fixed. Thx for letting me know !
