### ISSUE TITLE
About zoom

### ISSUE THREAD

**Issue by mfe** [mikrosimage/duke#53]
When maximizing Duke window, zoom remains at 0.5.
Zooming with the wheel doesn't allow me to go to 1.0 (best I can have is 1.06).
And it isn't centered. That forces me to pan to have the canvas in the center of the window.

Anyway, I'm using Duke for a week for testing purpose : :sparkling_heart:

**Comment by gchatelet** [comment]
You can hit the `f` key to cycle though the different fit modes. Would it work for you ?

**Comment by mfe** [comment]
Yes but I still think that fitting when maximizing should be the default behaviour.
